// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ollodan.Api.Data;

#nullable disable

namespace Ollodan.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524164939_AddOrderHistory")]
    partial class AddOrderHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Ollodan.Api.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdminMemberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowSuggestions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRepeating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Phase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SwishNote")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WinningProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdminSecret");

                    b.HasIndex("WinningProductId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.HasIndex("GroupId", "MemberId")
                        .IsUnique();

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.OrderRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdjustedTotalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumOrderQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedTotalQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("OrderRounds");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.OrderRoundLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AdjustedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderRoundId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderRoundId");

                    b.ToTable("OrderRoundLines");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AddedByMemberId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CaseSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumOrderQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystembolagetProductId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedByMemberId");

                    b.HasIndex("GroupId", "SystembolagetProductId")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProductId");

                    b.HasIndex("GroupId", "MemberId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.Group", b =>
                {
                    b.HasOne("Ollodan.Api.Entities.Product", "WinningProduct")
                        .WithMany()
                        .HasForeignKey("WinningProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WinningProduct");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.Member", b =>
                {
                    b.HasOne("Ollodan.Api.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.OrderLine", b =>
                {
                    b.HasOne("Ollodan.Api.Entities.Group", "Group")
                        .WithMany("OrderLines")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ollodan.Api.Entities.Member", "Member")
                        .WithOne("OrderLine")
                        .HasForeignKey("Ollodan.Api.Entities.OrderLine", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.OrderRound", b =>
                {
                    b.HasOne("Ollodan.Api.Entities.Group", "Group")
                        .WithMany("OrderRounds")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.OrderRoundLine", b =>
                {
                    b.HasOne("Ollodan.Api.Entities.OrderRound", "OrderRound")
                        .WithMany("Lines")
                        .HasForeignKey("OrderRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderRound");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.Product", b =>
                {
                    b.HasOne("Ollodan.Api.Entities.Member", "AddedByMember")
                        .WithMany()
                        .HasForeignKey("AddedByMemberId");

                    b.HasOne("Ollodan.Api.Entities.Group", "Group")
                        .WithMany("Products")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByMember");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.Vote", b =>
                {
                    b.HasOne("Ollodan.Api.Entities.Group", "Group")
                        .WithMany("Votes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ollodan.Api.Entities.Member", "Member")
                        .WithMany("Votes")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ollodan.Api.Entities.Product", "Product")
                        .WithMany("Votes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.Group", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("OrderLines");

                    b.Navigation("OrderRounds");

                    b.Navigation("Products");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.Member", b =>
                {
                    b.Navigation("OrderLine");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.OrderRound", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Ollodan.Api.Entities.Product", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
